Add yarn install
Since I uncommented the yarn test and there was no yarn install, the
script cannot find jest.  This time to test it I ran the script except
for the uploading parts, and it passes.

Error: https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/983387701#L103